# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-18 12:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='filler',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fill', to=settings.AUTH_USER_MODEL),
        ),
    ]
