# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-18 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0003_auto_20190318_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='answeredquestion',
            name='Answer',
            field=models.CharField(default='A', max_length=10),
            preserve_default=False,
        ),
    ]
